export const SET_OSCILLATOR_OUTPUT = 'SET_OSCILLATOR_OUTPUT';
export const SET_NOTE_PITCH = 'SET_NOTE_PITCH';
export const SET_NOTE_PLAYING = 'SET_NOTE_PLAYING';
export const SET_NOTE_VOLUME = 'SET_NOTE_VOLUME';
export const SET_OSCILLATOR_HOLD = 'SET_OSCILLATOR_HOLD';
