export const SET_VOLUME_ENVELOPE_ATTACK = 'SET_VOLUME_ENVELOPE_ATTACK';
export const SET_VOLUME_ENVELOPE_DECAY = 'SET_VOLUME_ENVELOPE_DECAY';
export const SET_VOLUME_ENVELOPE_SUSTAIN = 'SET_VOLUME_ENVELOPE_SUSTAIN';
export const SET_VOLUME_ENVELOPE_HOLD = 'SET_VOLUME_ENVELOPE_HOLD';
export const SET_VOLUME_ENVELOPE_RELEASE = 'SET_VOLUME_ENVELOPE_RELEASE';
